services:
  webhook:
    build: .
    ports:
      - "8099:8000"
    restart: unless-stopped
    container_name: ms-sincronizador-tickets-webhook
    env_file:
      - .env
    volumes:
      - .:/app